"""
Django settings for rankingProject project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-4#-$o+8+#vgzq17*3%!66hsy(0@5^%9v_tw8osz)y33260@xzn'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["127.0.0.1:8000",
                 "127.0.0.1",
                 "ec2-18-183-27-23.ap-northeast-1.compute.amazonaws.com:8000",
                 'ec2-18-183-27-23.ap-northeast-1.compute.amazonaws.com',]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'hololiveRankingApp.apps.HololiverankingConfig',
    'import_export',#20220701#
    'django.contrib.humanize',#20221112
    'hololiveRankingApp.templatetags.numeral_system',#202211162027
    'hololiveRankingApp.templatetags.simple_calc',#202211191251
    'widget_tweaks', #202211210751
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'rankingProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'rankingProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

with open(BASE_DIR / './SECRET/AWS_PASSWORD2.txt', 'r', encoding='UTF-8') as f:
    PASSWORDS = f.read().splitlines()
password = PASSWORDS[0]#RDSは一行目の文字列がパスワード

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'hololiveRankingApp', #　AWS RDS DB 名
        'USER': 'admin', # AWS RDS マスターユーザー名
        'HOST': 'hololiverankingdb.ckz8uo4hzyoc.ap-northeast-1.rds.amazonaws.com',# AWS RDS エンドポイント
        'PORT': '3306', #AWS RDS ポート名
        'PASSWORD': password,#"password"
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'ja'#en-us

TIME_ZONE = 'Asia/Tokyo'#UTC

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/


STATIC_ROOT = BASE_DIR / 'static'

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'assets/')
]

MEDIA_ROOT = BASE_DIR / 'assets/images'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'login'
# LOGIN_URL = 'hololiveRankingApp/login/'

LOGOUT_URL = 'logout'
# LOGOUT_URL = 'hololiveRankingApp/logout'
LOGIN_REDIRECT_URL = 'top'

NUMBER_GROUPING = 3

