# Generated by Django 3.2 on 2022-11-06 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnotherPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('snsURL', models.URLField(default='https://www.youtube.com/')),
                ('snsUserName', models.CharField(default='@Twitter', max_length=100)),
            ],
            options={
                'verbose_name_plural': '外部の方々',
            },
        ),
        migrations.CreateModel(
            name='Arranger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arranger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hololiveRankingApp.anotherperson')),
            ],
            options={
                'verbose_name_plural': '2:編曲家',
            },
        ),
        migrations.CreateModel(
            name='Composer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hololiveRankingApp.anotherperson')),
            ],
            options={
                'verbose_name_plural': '1:作曲家',
            },
        ),
        migrations.CreateModel(
            name='CoStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coStar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hololiveRankingApp.anotherperson')),
            ],
            options={
                'verbose_name_plural': '7:共演者',
            },
        ),
        migrations.CreateModel(
            name='FalseNameCorrect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('falseName', models.CharField(max_length=100)),
                ('trueName', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'カンマ入りタイトル修正',
            },
        ),
        migrations.CreateModel(
            name='hololiveChannel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('age', models.DateField(null=True)),
                ('channelId', models.CharField(max_length=100, null=True)),
                ('thumbnailDefault', models.URLField(null=True)),
                ('thumbnailMedium', models.URLField(null=True)),
                ('thumbnailHigh', models.URLField(null=True)),
                ('description', models.TextField(null=True)),
                ('lastUpdateDate', models.DateField(default='2022-08-03')),
            ],
            options={
                'verbose_name_plural': 'ホロライブチャンネル',
            },
        ),
        migrations.CreateModel(
            name='hololiveGenerations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GenName', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': '何期生',
            },
        ),
        migrations.CreateModel(
            name='Illustrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illustrator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hololiveRankingApp.anotherperson')),
            ],
            options={
                'verbose_name_plural': '6:イラスト',
            },
        ),
        migrations.CreateModel(
            name='ListOfJobTitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Position', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': '役職',
            },
        ),
        migrations.CreateModel(
            name='Lyricist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lyricist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hololiveRankingApp.anotherperson')),
            ],
            options={
                'verbose_name_plural': '0:作詞家',
            },
        ),
        migrations.CreateModel(
            name='Mixer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mixer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hololiveRankingApp.anotherperson')),
            ],
            options={
                'verbose_name_plural': '3:ミックス',
            },
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hololiveRankingApp.anotherperson')),
            ],
            options={
                'verbose_name_plural': '4:音楽',
            },
        ),
        migrations.CreateModel(
            name='OldResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('videoId', models.CharField(max_length=100, null=True)),
                ('viewCount', models.IntegerField(null=True)),
                ('likeCount', models.IntegerField(null=True)),
                ('videoAge', models.DateField(null=True)),
                ('aggregationDate', models.DateField(null=True)),
            ],
            options={
                'verbose_name_plural': 'ホロ日別結果(Old)',
            },
        ),
        migrations.CreateModel(
            name='OriginalSinger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originalSinger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hololiveRankingApp.anotherperson')),
            ],
            options={
                'verbose_name_plural': '8:本家歌い手',
            },
        ),
        migrations.CreateModel(
            name='VideoEditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoEditor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hololiveRankingApp.anotherperson')),
            ],
            options={
                'verbose_name_plural': '5:動画',
            },
        ),
        migrations.CreateModel(
            name='videoTypeJudgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': '動画の種類',
            },
        ),
        migrations.CreateModel(
            name='VideoInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('videoId', models.CharField(max_length=100, null=True)),
                ('videoAge', models.DateField(null=True)),
                ('videoCondition2', models.BooleanField(choices=[(False, '非公開or削除'), (True, '公開')], default=True, help_text='一日一回チェックして公開か否か確認している')),
                ('description', models.TextField(null=True)),
                ('tags', models.TextField(default='[]', null=True)),
                ('lastUpdateDate', models.DateField(null=True)),
                ('arranger', models.ManyToManyField(to='hololiveRankingApp.Arranger')),
                ('coStar', models.ManyToManyField(to='hololiveRankingApp.CoStar')),
                ('composer', models.ManyToManyField(to='hololiveRankingApp.Composer')),
                ('illust', models.ManyToManyField(to='hololiveRankingApp.Illustrator')),
                ('inst', models.ManyToManyField(to='hololiveRankingApp.Musician')),
                ('lyricist', models.ManyToManyField(help_text='こっちが正しい', to='hololiveRankingApp.Lyricist')),
                ('mix', models.ManyToManyField(to='hololiveRankingApp.Mixer')),
                ('movie', models.ManyToManyField(to='hololiveRankingApp.VideoEditor')),
                ('originalSinger', models.ManyToManyField(to='hololiveRankingApp.OriginalSinger')),
                ('performer', models.ManyToManyField(to='hololiveRankingApp.hololiveChannel2')),
                ('videoType', models.ManyToManyField(to='hololiveRankingApp.videoTypeJudgement')),
            ],
            options={
                'verbose_name_plural': 'ホロ全曲情報',
            },
        ),
        migrations.CreateModel(
            name='hololiveSongsResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregationDate', models.DateField(null=True)),
                ('viewCount', models.IntegerField(null=True)),
                ('likeCount', models.IntegerField(null=True)),
                ('viewCount7', models.IntegerField(default=0, null=True)),
                ('likeCount7', models.IntegerField(default=0, null=True)),
                ('viewCount30', models.IntegerField(default=0, null=True)),
                ('likeCount30', models.IntegerField(default=0, null=True)),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hololiveRankingApp.videoinfo')),
            ],
            options={
                'verbose_name_plural': 'ホロ日別結果',
            },
        ),
        migrations.AddField(
            model_name='hololivechannel2',
            name='category',
            field=models.ManyToManyField(to='hololiveRankingApp.hololiveGenerations'),
        ),
        migrations.CreateModel(
            name='AutoChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('channelId', models.CharField(max_length=100, null=True)),
                ('lastUpdateDate', models.DateField(default='2022-08-20')),
                ('info', models.ManyToManyField(to='hololiveRankingApp.hololiveChannel2')),
            ],
            options={
                'verbose_name_plural': 'ホロライブチャンネル(自動生成)',
            },
        ),
        migrations.AddField(
            model_name='anotherperson',
            name='category',
            field=models.ManyToManyField(to='hololiveRankingApp.ListOfJobTitles'),
        ),
    ]
